export const FontSetting = {
  "P-BL": require("../assets/fonts/Poppins-Black.ttf"),
  "P-BLI": require("../assets/fonts/Poppins-BlackItalic.ttf"),
  "P-BO": require("../assets/fonts/Poppins-Bold.ttf"),
  "P-BOI": require("../assets/fonts/Poppins-BoldItalic.ttf"),
  "P-EBO": require("../assets/fonts/Poppins-ExtraBold.ttf"),
  "P-EBOI": require("../assets/fonts/Poppins-ExtraBoldItalic.ttf"),
  "P-EL": require("../assets/fonts/Poppins-ExtraLight.ttf"),
  "P-ELI": require("../assets/fonts/Poppins-ExtraLightItalic.ttf"),
  "P-I": require("../assets/fonts/Poppins-Italic.ttf"),
  "P-L": require("../assets/fonts/Poppins-Light.ttf"),
  "P-LI": require("../assets/fonts/Poppins-LightItalic.ttf"),
  "P-M": require("../assets/fonts/Poppins-Medium.ttf"),
  "P-MI": require("../assets/fonts/Poppins-MediumItalic.ttf"),
  "P-R": require("../assets/fonts/Poppins-Regular.ttf"),
  "P-SB": require("../assets/fonts/Poppins-SemiBold.ttf"),
  "P-SBI": require("../assets/fonts/Poppins-SemiBoldItalic.ttf"),
  "P-T": require("../assets/fonts/Poppins-Thin.ttf"),
  "P-TI": require("../assets/fonts/Poppins-ThinItalic.ttf"),
};
